# create two functions: the first one returns a list of functions used to cache
# the inverse of a matrix. The second one actually calculates the inverse, 
# unless it has already been cached, in which case it just returns the cache.

makeCacheMatrix <- function(x = matrix()) { #new function, that accepts one argument (x) as a matrix
  m <- NULL #assign m vector NULL value
  set <- function(y) {#our first function. set x and m outside function scope
    x <<- y
    m <<- NULL
  }
  get <- function() x # just return the value of x, the matrix to be inverted
  setmatrix <- function(inverse) m <<- inverse # save the value of the inverse of the matrix to m, outside function scope
  getmatrix <- function() m # just return the value of the inverse matrix
  list(set = set, get = get,
       setmatrix = setmatrix,
       getmatrix = getmatrix) # return the functions previously defined
}

cacheSolve <- function(x, ...) { #new function. accepts the list of functions generated by the makeCacheMatrix function
  m <- x$getmatrix() # save value of matrix to m, scoped inside function
  if(!is.null(m)) { # if m is not null, it means you've already run this function and the value is cached. return a message and the m vector.
    message("getting cached data")
    return(m)
  }
  data <- x$get() # if m is NULL, the function continues. get the matrix
  m <- solve(data, ...) # invert the matrix and assign it to m
  x$setmatrix(m) # set the m vector to the inverted matrix, outside function scope
  m # return the inverted matrix
}

makeVector <- function(x = numeric()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setmean <- function(mea) m <<- mea
  getmean <- function() m
  list(set = set, get = get,
       setmean = setmean,
       getmean = getmean)
}

cacheMean <- function(x, ...) {
  m <- x$getmean()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- mean(data, ...)
  x$setmean(m)
  m
}